module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
      ],
    ],
    'subject-case': [0],
    'subject-empty': [2, 'never'],
    'subject-full-stop': [2, 'never', '.'],
    'header-max-length': [2, 'always', 100],
    'body-max-line-length': [2, 'always', 200],
    'scope-empty': [1, 'never'],
    'scope-case': [0],
    'scope-enum': [
      1,
      'always',
      [
        'catalog',
        'details',
        'payment',
        'contact',
        'cart',
        'checkout',
        'home',
        'testimonios',
        'header',
        'footer',
        'navbar',
        'hero',
        'benefits',
        'seo',
        'db',
        'config',
        'ci',
        'env',
        'devcontainer',
        'vscode',
        'agents',
        'docs',
        'deps',
        'security',
        'a11y',
        'perf',
        'styles',
        'utils',
        'types',
        'layouts',
        'components',
        'pages',
        'scripts',
        'assets',
        'release',
      ],
    ],
    'body-leading-blank': [1, 'always'],
    'footer-leading-blank': [1, 'always'],
  },
};
